version: '3.3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-web
    ports:
      - "8000:80"
    volumes:
      - ./php/src:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres-db
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
